### ISSUE TITLE
Get VDM* libs from the overturetool/documentation repo instead of using local versions

### ISSUE THREAD

**Issue by joey-coleman** [overturetool/example-packager#1]
The build needs to change to bundle the canonical versions of the VDM SL/++/RT libraries in the [overturetool/documentation repo](https://github.com/overturetool/documentation) instead of bundling the versions in the local resource folders.

**Comment by joey-coleman** [comment]
If the issue reported in overturetool/overture#363 is in the library in the overturetool/documentation repo, raise an issue there to track the fix.

**Comment by peterwvj** [comment]
This needs to be fixed!  @ldcouto  @lausdahl

**Comment by peterwvj** [comment]
By the way, the canonical libs are not in the documentation repo. They are in the main repo documentation folder

**Comment by ldcouto** [comment]
Ok, this is fixed now. Need to make a new release of the plugin before we close the issue.

**Comment by ldcouto** [comment]
New version released. Documentation repo also updated (https://github.com/overturetool/documentation/commit/975f050af62cbb93f0204bf6a23f740fb8bb3adf)
